name: Build master

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - 'v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:

      - name: Check out
        uses: actions/checkout@v3

      - name: Get time
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Build
        uses: tobyxdd/go-cross-build@3d5409b1f31e99ed87651195a29f5aefea23e77c
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          GOFLAGS: "-tags=gpl"
          CGO_ENABLED: "0"
        with:
          name: hysteria
          dest: dist
          ldflags: -w -s -X main.appCommit=${{ github.sha }} -X main.appDate=${{ env.TIME }}
          platforms: 'darwin/amd64, darwin/arm64, windows/amd64, windows/386, linux/amd64, linux/386, linux/arm, linux/arm64, linux/s390x, linux/mipsle, freebsd/amd64, freebsd/386, freebsd/arm, freebsd/arm64'
          package: cmd
          compress: false

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
